local_backend: true

publish_mode: editorial_workflow

site_url: https://decap-test-rimdev.netlify.app
display_url: https://decap-test-rimdev.netlify.app

backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: Create {{collection}} “{{slug}}”
    update: Update {{collection}} “{{slug}}”
    delete: Delete {{collection}} “{{slug}}”
    uploadMedia: Upload “{{path}}”
    deleteMedia: Delete “{{path}}”
    openAuthoring: '{{message}}'

collections:
  - name: "carriers" # Used in routes, e.g., /admin/collections/carriers
    label: "Carriers" # Used in the UI
    folder: "src/content/carriers" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    format: frontmatter
    preview_path: carriers/{{slug}}
    fields: # The fields for each document, usually in frontmatter
      - { label: "Layout", name: "layout", widget: "hidden", default: "../../layouts/CarrierLayout.astro", required: false}
      - { label: "Carrier Title", name: "title", widget: "string" }
      - { label: "Draft", name: "isDraft", widget: "boolean", required: false, default: false}
      - label: "Address"
        name: "address"
        widget: "object"
        collapsed: true
        fields: 
          - {label: "Street Address", name: "street", widget: "string"}
          - {label: "City", name: "city", widget: "string"}
      - label: "Company Information",
        name: "companyInformation",
        widget: "object",
        fields: 
          - label: "Carrier Logo"
            name: "carrierLogo"
            widget: "image"
          - label: "Administrative Office Mailing Address"
            name: "adminMailingAddress"
            widget: "object"
            fields: 
              - { label: 'Address Line 1', name: 'addressLine1', widget: 'string' }
              - { label: 'Address Line 2', name: 'addressLine2', widget: 'string', required: false }
          - label: "Overnight Mailing Address" 
            name: "overnightMailingAddress"
            widget: "object"
            fields: 
              - { label: 'Address Line 1', name: 'addressLine1', widget: 'string' }
              - { label: 'Address Line 2', name: 'addressLine2', widget: 'string', required: false }
          - label: 'Broker Support'
            name: 'brokerSupport'
            widget: 'object'
            fields: 
              - { label: 'Phone', name: 'phone', widget: 'string' }
              - { label: 'Email', name: 'email', widget: 'string' }
              - { label: 'Fax', name: 'fax', widget: 'string' }
          - label: 'New Business'
            name: 'newBusiness'
            widget: 'object'
            fields: 
              - { label: 'Phone', name: 'phone', widget: 'string' }
              - { label: 'Email', name: 'email', widget: 'string' }
              - { label: 'Fax', name: 'fax', widget: 'string' }
          - label: 'Policyowner Services/Member Services/Customer Service'
            name: 'policyOwnerServices'
            widget: 'object'
            fields: 
              - { label: 'Phone', name: 'phone', widget: 'string' }
              - { label: 'Email', name: 'email', widget: 'string' }
              - { label: 'Fax', name: 'fax', widget: 'string' }
          - { label: "Producer Portal", name: "producerPortal", widget: "string"}

media_folder: "src/assets/images" # Location where files will be stored in the repo
public_folder: "src/assets/images" # The src attribute for uploaded media