# local_backend:
#   # when using a custom proxy server port
#   url: http://localhost:8081/admin
#   # when accessing the local site from a host other than 'localhost' or '127.0.0.1'
#   allowed_hosts: ['192.168.0.1']

publish_mode: editorial_workflow

site_url: https://decap-test-rimdev.netlify.app
display_url: https://decap-test-rimdev.netlify.app

backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: Create {{collection}} “{{slug}}”
    update: Update {{collection}} “{{slug}}”
    delete: Delete {{collection}} “{{slug}}”
    uploadMedia: Upload “{{path}}”
    deleteMedia: Delete “{{path}}”
    openAuthoring: '{{message}}'

collections:
  - name: "carriers" # Used in routes, e.g., /admin/collections/carriers
    label: "Carriers" # Used in the UI
    folder: "src/content/carriers" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    format: frontmatter
    preview_path: carriers/{{slug}}
    fields: # The fields for each document, usually in frontmatter
      - {label: "Layout", name: "layout", widget: "hidden", default: "../../layouts/CarrierLayout.astro"}
      - { label: "Carrier Title", name: "carrierTitle", widget: "string" } 
      - {label: "Draft", name: "isDraft", widget: "boolean", default: false}
      - { label: "Description", name: 'description', widget: "string" }
      - { label: "Carrier Logo", name: "carrierLogo", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Administrative Office Mailing Address", name: "adminMailingAddress", widget: "string"}
      - { label: "Overnight Mailing Address", name: "overnightMailingAddress", widget: "string"}

media_folder: "src/assets/images" # Location where files will be stored in the repo
public_folder: "src/assets/images" # The src attribute for uploaded media