local_backend: true

publish_mode: editorial_workflow

site_url: https://decap-test-rimdev.netlify.app
display_url: https://decap-test-rimdev.netlify.app

backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: Create {{collection}} “{{slug}}”
    update: Update {{collection}} “{{slug}}”
    delete: Delete {{collection}} “{{slug}}”
    uploadMedia: Upload “{{path}}”
    deleteMedia: Delete “{{path}}”
    openAuthoring: '{{message}}'

collections:
  - name: "carriers" # Used in routes, e.g., /admin/collections/carriers
    label: "Carriers" # Used in the UI
    folder: "src/content/carriers" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    format: frontmatter
    preview_path: carriers/{{slug}}
    fields: # The fields for each document, usually in frontmatter
      - { label: "Layout", name: "layout", widget: "hidden", default: "../../layouts/CarrierLayout.astro", required: false}
      - { label: "Carrier Title", name: "title", widget: "string" }
      - { label: "Draft", name: "isDraft", widget: "boolean", required: false, default: false}
      - label: "Company Information"
        name: "companyInfo"
        widget: "object"
        fields: 
          - label: "Carrier Logo"
            name: "carrierLogo"
            widget: "image"
          - label: "Administrative Office Mailing Address"
            name: "adminMailing"
            widget: "object"
            fields: 
              - { label: 'Address Line 1', name: 'addressLine1', widget: 'string' }
              - { label: 'Address Line 2', name: 'addressLine2', widget: 'string', required: false }
          - label: "Overnight Mailing Address" 
            name: "overnightMailing"
            widget: "object"
            fields: 
              - { label: 'Address Line 1', name: 'addressLine1', widget: 'string' }
              - { label: 'Address Line 2', name: 'addressLine2', widget: 'string', required: false }
          - label: 'Broker Support'
            name: 'brokerSupport'
            widget: 'object'
            fields: 
              - { label: 'Phone', name: 'phone', widget: 'string' }
              - { label: 'Email', name: 'email', widget: 'string' }
              - { label: 'Fax', name: 'fax', widget: 'string' }
          - label: 'New Business'
            name: 'newBusiness'
            widget: 'object'
            fields: 
              - { label: 'Phone', name: 'phone', widget: 'string' }
              - { label: 'Email', name: 'email', widget: 'string' }
              - { label: 'Fax', name: 'fax', widget: 'string' }
          - label: 'Policyowner Services/Member Services/Customer Service'
            name: 'policyOwnerServices'
            widget: 'object'
            fields: 
              - { label: 'Phone', name: 'phone', widget: 'string' }
              - { label: 'Email', name: 'email', widget: 'string' }
              - { label: 'Fax', name: 'fax', widget: 'string' }
          - { label: "Producer Portal", name: "producerPortal", widget: "string"}
      - label: "Certification Information"
        name: "certInfo"
        widget: "object"
        summary: "[Carrier] [Year] Certification"
        fields: 
          - { label: "Instructions for the Following Products:", name: "productInstructions", widget: "text"}
          - label: "Certification Start Date:" 
            name: "certStartDate" 
            widget: "datetime"
            default: ""
            # e.g. 24.12.2021,
            date_format: "DD.MM.YYYY"
            # e.g. 21:07,
            time_format: "HH:mm"
            format: "LLL"
            picker_utc: true
          - label: "Is there a Deadline to Complete Certifications for New Agents?:"
            name: "agentDeadline"
            widget: "string"
          - label: "Is there a Deadline to Complete Certifications for Current Agents to Receive Renewal Commissions?:"
            name: "agentDeadlineRenewal"
            widget: "string"
          - label: "Certification Link:" 
            name: "certLink"
            widget: "string"
          - { label: "Certification Reference Materials Available:", name: "certReferenceMaterials", widget: "string"}
          - { label: "Is AHIP or Other Equivalent Provider Training Required?", name: "providerTrainingRequired", widget: "string"}
          - { label: "What is the Cost of AHIP or Other Equivalent Provider Training?", name: "providerTrainingCost", widget: "string"}
          - { label: "Does Carrier Reimburse for AHIP or Other Equivalent Provider Training?", name: "providerTrainingReimburse", widget: "string"}
          - { label: "Can AHIP or Other Equivalent Provider Training Be Used for Compliance Credit?", name: "providerTrainingComplianceCredit", widget: "string"}
          - { label: "Certification Compliance Modules:", name: "certComplianceModules", widget: "string"}
          - { label: "Certification Product Modules", name: "certProductModules", widget: "string"}
          - { label: "Is Face-to-Face Training Required?", name: "faceToFaceTrainingRequired", widget: "string"}
          - { label: "Will Certifying for [Upcoming Certification Year] Allow Me to Sell [Previous Certification Year] Products?", name: "certifyingToSellProducts", widget: "string"}
          - { label: "Are Additional Steps Required for Those Certifying for the First Time Versus Those Who Are Recertifying?", name: "additionalStepsRequired", widget: "string"}
          - { label: "How Do I Retrieve My Username and Password?", name: "retrieveUsernameAndPassword", widget: "string"}
          - { label: "Who Do I Contact at Carrier to Confirm Certification?", name: "contactCarrierCornfirmCert", widget: "string"}
      - label: "Submitting Business"
        name: "submittingBusiness"
        widget: "object"
        fields:
          - { label: "Important Information:", name: "importantInfo", widget: "string"}
          - { label: "How to Submit Business with [Carrier Name]:", name: "howToSubmitBusiness", widget: "string"}
          - label: 'Paper Applications'
            name: 'paperApps'
            widget: 'object'
            fields: 
              - { label: 'Fax Number', name: 'faxNumber', widget: 'string' }
              - { label: 'Mailing Address', name: 'mailingAddress', widget: 'string' }
          - label: 'Online Enrollments'
            name: 'onlineEnrollments'
            widget: 'object'
            fields: 
              - { label: 'Website', name: 'website', widget: 'string' }
              - { label: 'Other Information', name: 'otherInfo', widget: 'string', required: false }
              - { label: 'Other Information', name: 'otherInfo2', widget: 'string', required: false }
          - { label: "Contact for Submitting Business Inquiries", name: "contactForSubmittingBusinessInquiries", widget: "string"}
      - label: "Commissions"
        name: "commissions"
        widget: "object"
        fields: 
          - { label: "General Information:", name: "generalInfo", widget: "string"}
          - { label: "How to Access [Carrier Name] Commission Statements Online:", name: "accessCommissionStatesmentsOnline", widget: "string"}
          - { label: "Contact for Commission-Related Inquiries:", name: "contactForCommissionRelatedInquiries", widget: "string"}
      - label: "Supplies"
        name: "supplies"
        widget: "object"
        fields: 
          - { label: "How to Order Supplies for [Carrier Name]:", name: "howToOrderSupplies", widget: "string"}
          - { label: "Contact for Ordering Supplies Inquiries:", name: "contactForOrderingSupplies", widget: "string"}
      - { label: "Body", name: "body", widget: "markdown", required: false }

media_folder: "src/assets/images" # Location where files will be stored in the repo
public_folder: "src/assets/images" # The src attribute for uploaded media